import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import { Inter, Lusitana, Roboto, Prompt } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import { ReactNode } from 'react';
import Navbar from '@/components/navbar/navbar';

// const inter = Inter({ subsets: ['latin'] });
// const lusitana = Lusitana({ weight: ['400', '700'], subsets: ['latin'] });
// const roboto = Roboto({ weight: ['400', '700', '500'], subsets: ['latin'] });
const prompt = Prompt({ weight: ['400', '700', '500'], subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface MainLayoutProps {
    children: ReactNode;
}

export default function RootLayout({ children }: MainLayoutProps) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={prompt.className}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <main className='flex flex-col w-full h-screen'>
                        {children}
                    </main>
                    <Toaster richColors />
                </ThemeProvider>
            </body>
        </html>
    );
}
